% function to create base filename from design parameters

function P = CreateFileBase(P)

if isfield(P,'celltype') && strcmp(P.celltype,'blockTet')
    P.fileBase = ['a',num2str(P.a*1e9,'%.0f'),'nm_',...
              'w',num2str(P.w*1e9,'%.0f'),'nm_',...
              'hx',num2str(P.hx*1e9,'%.0f'),'nm_',...
              'hy',num2str(P.hy*1e9,'%.0f'),'nm_',...
              'nh',num2str(P.nholes,'%.0f'),'_',...
              'nd',num2str(P.ndef,'%.0f'),'_',...
              'aD',num2str(P.a_ctr*1e9,'%.0f'),'nm_',...
              'wD',num2str(P.w_ctr*1e9,'%.0f'),'nm_',...
              'hxD',num2str(P.hx_ctr*1e9,'%.0f'),'nm_',...
              'hyD',num2str(P.hy_ctr*1e9,'%.0f'),'nm_',...
              'X',num2str(P.mevenx),...
              'Y',num2str(P.meveny),...
              'Z',num2str(P.mevenz)];
else
    P.fileBase = ['a',num2str(P.a*1e9,'%.0f'),'nm_',...
              'nh',num2str(P.nholes,'%.0f'),'_',...
              'nd',num2str(P.ndef,'%.0f'),'_',...
              'nw',num2str(P.wvgmir,'%.0f'),'_',...
              'w',num2str(P.w*1e9,'%.0f'),'nm_',...
              'hx',num2str(P.hx*1e9,'%.0f'),'nm_',...
              'hy',num2str(P.hy*1e9,'%.0f'),'nm_',...
              'o',num2str(P.oblong,'%.4f'),'_',...
              'd',num2str(P.maxdef,'%.4f')];
    if isfield(P,'taperTo') && strcmp(P.taperTo,'custom')
        P.fileBase = [P.fileBase,'_',...
                      'aC',num2str(P.a_ctr*1e9,'%.0f'),'nm_',...
                      'hxC',num2str(P.hx_ctr*1e9,'%.0f'),'nm_',...
                      'hyC',num2str(P.hy_ctr*1e9,'%.0f'),'nm'];
    end
end
          
if strcmp(P.xsect,'tri')
    P.fileBase = [num2str(P.theta,'%.0f'),'o_',P.fileBase];
elseif strcmp(P.xsect,'rect')
    P.fileBase = ['th',num2str(P.th*1e9,'%.0f'),'nm_',P.fileBase];
end
if isfield(P,'rxtal') && isfield(P,'rxtalInFilename') && P.rxtalInFilename == 1
    P.fileBase = ['rxt',num2str(P.rxtal,'%.0f'),'o_',P.fileBase];
end
if isfield(P,'asymCav') && P.asymCav && isfield(P,'PL')
    P.fileBase = [P.fileBase,'_'...
                  'nmL',num2str(P.PL.nholes-P.PL.ndef,'%.0f'),'_',...
                  'nwL',num2str(P.PL.wvgmir,'%.0f')];
end
if isfield(P,'shave')
    P.fileBase = [P.fileBase,'_sh',num2str(P.shave*1e9,'%.0f'),'nm'];
end
if isfield(P,'strPoint') && isfield(P,'nItr')
    P.fileBase = ['sp',num2str(P.strPoint),'_',...
                  'itr',num2str(P.nItr),'_',P.fileBase];
end
if isfield(P,'asymCav') && P.asym
    P.fileBase = ['asym_',P.fileBase];
end
if isfield(P,'prefname')
    P.fileBase = [P.prefname,'_',P.fileBase];
end
if isfield(P,'filRad') && P.filRad > 0
    fBase = [fBase,'_Rfil_',num2str(P.filRad*1e9,'%.1f'),'nm'];
end

end