% function to create base filename from design parameters

function P = CreateFileBase(P)

if isfield(P,'celltype') && strcmp(P.celltype,'blockTet')
    P.fileBase = ['a',num2str(P.a*1e9,'%.0f'),'nm_',...
              'w',num2str(P.w*1e9,'%.0f'),'nm_',...
              'hx',num2str(P.hx*1e9,'%.0f'),'nm_',...
              'hy',num2str(P.hy*1e9,'%.0f'),'nm_',...
              'nh',num2str(P.nholes,'%.0f'),'_',...
              'nd',num2str(P.ndef,'%.0f'),'_',...
              'aD',num2str(P.a_ctr*1e9,'%.0f'),'nm_',...
              'wD',num2str(P.w_ctr*1e9,'%.0f'),'nm_',...
              'hxD',num2str(P.hx_ctr*1e9,'%.0f'),'nm_',...
              'hyD',num2str(P.hy_ctr*1e9,'%.0f'),'nm_',...
              'X',num2str(P.mevenx),...
              'Y',num2str(P.meveny),...
              'Z',num2str(P.mevenz)];
elseif isfield(P,'celltype') && strcmp(P.celltype,'boomerang_v2')
    P.fileBase = ['boomerang_v2_','a',num2str(P.a*1e9,'%.0f'),'nm_',...
              'w',num2str(P.w*1e9,'%.0f'),'nm_',...
              'r',num2str(P.r*1e9,'%.0f'),'nm_',...
              'hi',num2str(P.hi*1e9,'%.0f'),'nm_',...
              'ho',num2str(P.ho*1e9,'%.0f'),'nm_',...
              'wi',num2str(P.wi*1e9,'%.0f'),'nm_',...
              'wo',num2str(P.wo*1e9,'%.0f'),'nm_',...
              'd',num2str(P.d*1e9,'%.0f'),'nm_',...
              'th',num2str(P.th*1e9,'%.0f'),'nm_',...
              'a_ctr',num2str(P.a_ctr*1e9,'%.0f'),'nm_',...
              'ho_ctr',num2str(P.ho_ctr*1e9,'%.0f'),'nm_',...
              'hi_ctr',num2str(P.hi_ctr*1e9,'%.0f'),'nm_',...
              'wo_ctr',num2str(P.wo_ctr*1e9,'%.0f'),'nm_',...
              'wi_ctr',num2str(P.wi_ctr*1e9,'%.0f'),'nm_',...
              'MN_left',num2str(P.MN_left,'%.0f'),'_',...
              'MN_right',num2str(P.MN_right,'%.0f'),'_',...
              'TN',num2str(P.TN,'%.0f'),'_',...
              'X',num2str(P.mevenx),...
              'Y',num2str(P.meveny),...
              'Z',num2str(P.mevenz)];
elseif isfield(P,'celltype') && strcmp(P.celltype,'snowflake')
    P.fileBase = ['snowflake_','a',num2str(P.a*1e9,'%.0f'),'nm_',...
              'w',num2str(P.w*1e9,'%.0f'),'nm_',...
              'r',num2str(P.r*1e9,'%.0f'),'nm_',...
              'hi',num2str(P.hi*1e9,'%.0f'),'nm_',...
              'ho',num2str(P.ho*1e9,'%.0f'),'nm_',...
              'wi',num2str(P.wi*1e9,'%.0f'),'nm_',...
              'wo',num2str(P.wo*1e9,'%.0f'),'nm_',...
              'd',num2str(P.d*1e9,'%.0f'),'nm_',...
              'th',num2str(P.th*1e9,'%.0f'),'nm_',...
              'a_ctr',num2str(P.a_ctr*1e9,'%.0f'),'nm_',...
              'ho_ctr',num2str(P.ho_ctr*1e9,'%.0f'),'nm_',...
              'hi_ctr',num2str(P.hi_ctr*1e9,'%.0f'),'nm_',...
              'wo_ctr',num2str(P.wo_ctr*1e9,'%.0f'),'nm_',...
              'wi_ctr',num2str(P.wi_ctr*1e9,'%.0f'),'nm_',...
              'MN_left',num2str(P.MN_left,'%.0f'),'_',...
              'MN_right',num2str(P.MN_right,'%.0f'),'_',...
              'TN',num2str(P.TN,'%.0f'),'_',...
              'X',num2str(P.mevenx),...
              'Y',num2str(P.meveny),...
              'Z',num2str(P.mevenz)];
else
    P.fileBase = ['a',num2str(P.a*1e9,'%.0f'),'nm_',...
              'nh',num2str(P.nholes,'%.0f'),'_',...
              'nd',num2str(P.ndef,'%.0f'),'_',...
              'nw',num2str(P.wvgmir,'%.0f'),'_',...
              'w',num2str(P.w*1e9,'%.0f'),'nm_',...
              'hx',num2str(P.hx*1e9,'%.0f'),'nm_',...
              'hy',num2str(P.hy*1e9,'%.0f'),'nm_',...
              'o',num2str(P.oblong,'%.4f'),'_',...
              'd',num2str(P.maxdef,'%.4f')];
end

% cross-cell phononic shield tokens. Additive and field-guarded: a caller that
% does not set the shield fields produces a byte-identical filename. Kept in
% sync with nanobeam/CreateFileBase.m per CLAUDE.md - either copy can win the
% path lookup, so the shield must be encoded in both.
%
% THE nsy TOKEN ENCODES THE Y CONVENTION, NOT JUST THE COUNT, because
% P.nShieldY means two different devices depending on P.meveny:
%   abs(P.meveny) == 1 (or P.meveny absent)  HALF-Y build. P.nShieldY is the
%       cell count in the simulated y >= 0 half, the physical device has
%       2*P.nShieldY rows, and the shield is mirror-symmetric about the beam.
%       Token: nsyH<half>_nsyP<physical>, spelled out so the convention cannot
%       be misread from a filename months later. THIS STRING IS UNCHANGED - it
%       must stay byte for byte what it was, or every cached .mat/.mph under
%       test/ is orphaned.
%   P.meveny == 0                            FULL-Y build. P.nShieldY is the
%       ABSOLUTE row count, all of it on the +y side of the beam, and the
%       shield bottom is flush with the beam bottom. Token: nsyF<absolute>.
%
% Without the distinction a full-y run and a half-y run at the same P.nShieldY
% would produce the same P.fileBase, and RunNanobeamFEM.m:64 - which skips the
% entire solve whenever a matching .mat AND .mph already sit in datLoc - would
% hand back the other build's result with nothing in the log to say so. The
% same argument is why the PML length is in here: without that token a Q vs
% PMLLen convergence sweep would silently reload the first run.
if isfield(P,'nShieldX') && isfield(P,'nShieldY')
    if isfield(P,'meveny') && abs(P.meveny) < 1
        nsyStr = ['nsyF',num2str(P.nShieldY,'%.0f')];
    else
        nsyStr = ['nsyH',num2str(P.nShieldY,'%.0f'),'_',...
                  'nsyP',num2str(2*P.nShieldY,'%.0f')];
    end
    P.fileBase = [P.fileBase,'_',...
                  'csA',num2str(P.aShield*1e9,'%.0f'),'nm_',...
                  'csH',num2str(P.hShield*1e9,'%.0f'),'nm_',...
                  'csW',num2str(P.wShield*1e9,'%.0f'),'nm_',...
                  'nsx',num2str(P.nShieldX,'%.0f'),'_',...
                  nsyStr];
    if isfield(P,'shieldPadLen') && P.shieldPadLen > 0
        P.fileBase = [P.fileBase,'_pad',num2str(P.shieldPadLen*1e9,'%.0f'),'nm'];
    end
    if isfield(P,'shieldFillet') && ~strcmp(P.shieldFillet,'none')
        P.fileBase = [P.fileBase,'_fil',P.shieldFillet];
    end
    if isfield(P,'solveMechPML') && P.solveMechPML && isfield(P,'PMLLen')
        P.fileBase = [P.fileBase,'_pml',num2str(P.PMLLen*1e9,'%.0f'),'nm'];
    end
end

if strcmp(P.xsect,'tri')
    P.fileBase = [num2str(P.theta,'%.0f'),'o_',P.fileBase];
elseif strcmp(P.xsect,'rect')
    P.fileBase = ['th',num2str(P.th*1e9,'%.0f'),'nm_',P.fileBase];
end
if isfield(P,'rxtal') && isfield(P,'rxtalInFilename') && P.rxtalInFilename == 1
    P.fileBase = ['rxt',num2str(P.rxtal,'%.0f'),'o_',P.fileBase];
end
if isfield(P,'asymCav') && P.asymCav && isfield(P,'PL')
    P.fileBase = [P.fileBase,'_'...
                  'nmL',num2str(P.PL.nholes-P.PL.ndef,'%.0f'),'_',...
                  'nwL',num2str(P.PL.wvgmir,'%.0f')];
end
if isfield(P,'shave')
    P.fileBase = [P.fileBase,'_sh',num2str(P.shave*1e9,'%.0f'),'nm'];
end
if isfield(P,'strPoint') && isfield(P,'nItr')
    P.fileBase = ['sp',num2str(P.strPoint),'_',...
                  'itr',num2str(P.nItr),'_',P.fileBase];
end
if isfield(P,'asymCav') && P.asym
    P.fileBase = ['asym_',P.fileBase];
end
if isfield(P,'prefname')
    P.fileBase = [P.prefname,'_',P.fileBase];
end
if isfield(P,'filRad') && P.filRad > 0
    fBase = [fBase,'_Rfil_',num2str(P.filRad*1e9,'%.1f'),'nm'];
end

end