function ds = solveOpticalBands(P)

%% make the file directory
if ~strcmp(P.datLoc(end),'\')
    datLoc = [P.datLoc,'\'];
else
    datLoc = P.datLoc;
end
% create directory to save files
if ~exist(datLoc,'dir')
    mkdir(datLoc)
end

% create base folder name (TODO: need to update)
if ~isfield(P,'fileBase')
    if strcmp(P.celltype,'2D_ribs')
        fBase = ['optical_2D_ribs_','a_',num2str(P.a*1e9,'%.0f'),'nm_',...
            'w_',num2str(P.w*1e9,'%.0f'),'nm',...
            'hi_',num2str(P.hi*1e9,'%.0f'),'nm_', ...
            'wi_',num2str(P.wi*1e9,'%.0f'),'nm_', ...
            'ho_',num2str(P.ho*1e9,'%.0f'),'nm_',...
            'wo_',num2str(P.wo*1e9,'%.0f'),'nm_',...
            'ai_',num2str(P.ai*1e9,'%.0f'),'nm_'];
        if isfield(P,'prefname')
            fBase = [P.prefname,'_',fBase];
        end
        P.fileBase = fBase;
    elseif strcmp(P.celltype,'cross')
        fBase = ['optical_cross_','a_',num2str(P.a*1e9,'%.0f'),'nm_',...
            'hc_',num2str(P.hc*1e9,'%.0f'),'nm',...
            'wc_',num2str(P.wc*1e9,'%.0f'),'nm_', ...
            'r1_',num2str(P.r1*1e9,'%.0f'),'nm_', ...
            'r2_',num2str(P.r2*1e9,'%.0f'),'nm_'];
        if isfield(P,'prefname')
            fBase = [P.prefname,'_',fBase];
        end
        P.fileBase = fBase;
    elseif strcmp(P.celltype,'boomerang')
        fBase = ['optical_boomerang_','a_',num2str(P.a*1e9,'%.0f'),'nm_',...
            'r_',num2str(P.r*1e9,'%.0f'),'nm',...
            'w_',num2str(P.w*1e9,'%.0f'),'nm_', ...
            'r1_',num2str(P.r1*1e9,'%.0f'),'nm_', ...
            'r2_',num2str(P.r2*1e9,'%.0f'),'nm_'];
        if isfield(P,'prefname')
            fBase = [P.prefname,'_',fBase];
        end
        P.fileBase = fBase;
    elseif strcmp(P.celltype,'boomerang_strip_v2')
        fBase = ['boomerang_strip_optical_',...
            'a_',num2str(P.a*1e9,'%.0f'),'nm_',...
            'r_',num2str(P.r*1e9,'%.0f'),'nm',...
            'w_',num2str(P.w*1e9,'%.0f'),'nm_', ...
            'hi_',num2str(P.hi*1e9,'%.0f'),'nm_', ...
            'ho_',num2str(P.ho*1e9,'%.0f'),'nm_', ...
            'wi_',num2str(P.wi*1e9,'%.0f'),'nm_', ...
            'wo_',num2str(P.wo*1e9,'%.0f'),'nm_', ...
            'th_',num2str(P.th*1e9,'%.0f'),'nm_', ...
            'r1_',num2str(P.r1*1e9,'%.0f'),'nm_', ...
            'r2_',num2str(P.r2*1e9,'%.0f'),'nm_'];
        if isfield(P,'prefname')
            fBase = [P.prefname,'_',fBase];
        end
        P.fileBase = fBase;
     elseif strcmp(P.celltype,'boomerang_strip')
        fBase = ['boomerang_strip_optical_',...
            'a_',num2str(P.a*1e9,'%.0f'),'nm_',...
            'r_',num2str(P.r*1e9,'%.0f'),'nm',...
            'w_',num2str(P.w*1e9,'%.0f'),'nm_', ...
            'h_',num2str(P.h*1e9,'%.0f'),'nm_', ...
            'd_',num2str(P.d1*1e9,'%.0f'),'nm_', ...
            'th_',num2str(P.th*1e9,'%.0f'),'nm_', ...
            'r1_',num2str(P.r1*1e9,'%.0f'),'nm_', ...
            'r2_',num2str(P.r2*1e9,'%.0f'),'nm_'];
        if isfield(P,'prefname')
            fBase = [P.prefname,'_',fBase];
        end
        P.fileBase = fBase;
    elseif strcmp(P.celltype,'snowflake')
        fBase = ['optical_snowflake_','a_',num2str(P.a*1e9,'%.0f'),'nm_',...
            'r_',num2str(P.r*1e9,'%.0f'),'nm',...
            'w_',num2str(P.w*1e9,'%.0f'),'nm_', ...
            'r1_',num2str(P.r1*1e9,'%.0f'),'nm_', ...
            'r2_',num2str(P.r2*1e9,'%.0f'),'nm_'];
        if isfield(P,'prefname')
            fBase = [P.prefname,'_',fBase];
        end
        P.fileBase = fBase;
        
    elseif strcmp(P.celltype,'hole')
        fBase = ['optical_hole_','a_',num2str(P.a*1e9,'%.0f'),'nm_',...
            'hx_',num2str(P.hx*1e9,'%.0f'),'nm',...
            'hy_',num2str(P.hy*1e9,'%.0f'),'nm',...
            'beam_width_',num2str(P.beam_width*1e9,'%.0f'),'nm',...
            'th_',num2str(P.th*1e9,'%.0f'),'nm'];
        if isfield(P,'prefname')
            fBase = [P.prefname,'_',fBase];
        end
        P.fileBase = fBase;
    elseif strcmp(P.celltype,'hole_strip')
        fBase = ['optical_holeStrip_','a_',num2str(P.a*1e9,'%.0f'),'nm_',...
            'r_',num2str(P.r*1e9,'%.0f'),'nm',...
            'b_',num2str(P.b*1e9,'%.0f'),'nm'];
        if isfield(P,'prefname')
            fBase = [P.prefname,'_',fBase];
        end
        P.fileBase = fBase;
    elseif strcmp(P.celltype,'hole_strip_wvg')
        fBase = ['optical_holeStrip_wvg_','a_',num2str(P.a*1e9,'%.0f'),'nm_',...
            'r_',num2str(P.r*1e9,'%.0f'),'nm',...
            'b_',num2str(P.b*1e9,'%.0f'),'nm'];
        if isfield(P,'prefname')
            fBase = [P.prefname,'_',fBase];
        end
        P.fileBase = fBase;
    elseif strcmp(P.celltype,'Snowflake_strip_1d')
        fBase = ['optical_snowflake_strip_','a_',num2str(P.a*1e9,'%.0f'),'nm_',...
            'b_',num2str(P.b*1e9,'%.0f'),'nm_',...
            'b_wvg_',num2str(P.b_wvg*1e9,'%.0f'),'nm_',...
            'r_',num2str(P.r*1e9,'%.0f'),'nm_',...
            'w_',num2str(P.w*1e9,'%.0f'),'nm_', ...
            'r1_',num2str(P.r1*1e9,'%.0f'),'nm_', ...
            'r2_',num2str(P.r2*1e9,'%.0f'),'nm_', ...
            'th_',num2str(P.th*1e9,'%.0f'),'nm_'];
        if isfield(P,'prefname')
            fBase = [P.prefname,'_',fBase];
        end
        P.fileBase = fBase;
    elseif strcmp(P.celltype,'rib')
        fBase = ['optical_rib_','a_',num2str(P.a*1e9,'%.0f'),'nm_',...
            's_',num2str(P.s*1e9,'%.0f'),'nm',...
            'w_',num2str(P.w*1e9,'%.0f'),'nm_', ...
            't_',num2str(P.t*1e9,'%.0f'),'nm_', ...
            'th_',num2str(P.th*1e9,'%.0f'),'nm_', ...
            'd_',num2str(P.d*180/pi,'%.0f'),'deg'];
        if isfield(P,'prefname')
            fBase = [P.prefname,'_',fBase];
        end
        P.fileBase = fBase;
    end
end
fBase = P.fileBase;

%% solve the optical band structure
if isempty(dir([datLoc,fBase,'_bds.mat']))
    tStart = tic;
    if P.bandStructureDim==3
        OpticalBand = runOpticalBand_3D(P);
    elseif P.bandStructureDim==2
        OpticalBand = runOpticalBand_2D(P);
    else 
        OpticalBand = runOpticalBand_1D(P);
    end
    
    % filter data below light line 
    c = 299792458;
    lightline = c*OpticalBand.kx_norm/2/P.a; % factor of 2 such that kx_norm runs from 0 to 0.5 * (2*pi/a)
    TE.F0 = OpticalBand.F;
    TEbelow = OpticalBand.F < lightline;    % check which bands are below lightline
    TE.F = OpticalBand.F.*TEbelow;        % filter out data below lightline
    TE.F(TE.F==0) = NaN;      % replace zeros with NaN so they don't get plotted

    % find gaps 
    [OpticalBand.midGap,OpticalBand.gapSize] = findGaps_optical(TE);
    % write to data structure 
    ds.opticalBand = OpticalBand;
%% plot bandstructure
if P.savebndplot
    if P.bandStructureDim==2
        figure; hold on
        maxFreqs = [0 0 0 0];

        p1 = plot(OpticalBand.k_norm,OpticalBand.F*1e-12,'ko','linewidth',2,'DisplayName','sym','MarkerSize',5);
        % plot the light lines 
        lightx = linspace(0,0.5,100);
        lighty1 = lightx*(3e8)/(P.a*(1e12));
        lighty2 = sqrt(1/4+(lightx./sqrt(3)).^2).*3e8./(P.a*(1e12));
        lighty3 = sqrt((0.5-lightx).^2 + (0.5/sqrt(3)-(lightx./sqrt(3))).^2)*(3e8)/(P.a*(1e12));
        hold on;
        light1 = plot(2*lightx,lighty1,'b-','linewidth',1);
        light2 = plot(1+2*lightx,lighty2,'b-','linewidth',1);
        light3 = plot(2+2*lightx,lighty3,'b-','linewidth',1);
        
        % plot optical bandgaps
        for k = 1:length(OpticalBand.gapSize)
            bgp = patch([0 3 3 0],(1e-12)*(OpticalBand.midGap(k) + 0.5*[OpticalBand.gapSize(k) ...
                OpticalBand.gapSize(k) -OpticalBand.gapSize(k) -OpticalBand.gapSize(k)]),180/255*[1 1 1],'EdgeColor','none');
            alpha(bgp,0.5);
        end
        
        % plot symmetric midgap frequencies
        for k = 1:length(OpticalBand.midGap)
            midfreqs = OpticalBand.midGap(k)*ones(length(OpticalBand.k_norm),1);
            plot(OpticalBand.k_norm,midfreqs*1e-12,'.--r','linewidth',0.5);
        end
      
        xlabel('k','FontSize',12);
        ylabel('Frequency (THz)','FontSize',12);
        amax = max([OpticalBand.F(:)])*1e-12;
        axis([0 3 0 amax]);
        %         axis tight
        set(gca,'XTick',[0; 1]);
        %         set(gca,'XTickLabel',{'G','C'},'fontname','symbol','fontsize',16)
        set(gca,'XTickLabel',{'\Gamma','X','M','\Gamma'},'fontsize',12);
        
        if strcmp(P.celltype,'2D_ribs')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'w = ',num2str(P.w*1e9,'%.0f'),'nm',...
                'hi = ',num2str(P.hi*1e9,'%.0f'),'nm, ',...
                'wi = ',num2str(P.wi*1e9,'%.0f'),'nm',...
                'ho = ',num2str(P.ho*1e9,'%.0f'),'nm, ',...
                'wo = ',num2str(P.wo*1e9,'%.0f'),'nm',...
                'ai = ',num2str(P.ai*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'cross')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'hc = ',num2str(P.hc*1e9,'%.0f'),'nm, ',...
                'wc = ',num2str(P.wc*1e9,'%.0f'),'nm',...
                'r1 = ',num2str(P.r1*1e9,'%.0f'),'nm',...
                'r2 = ',num2str(P.r2*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'boomerang_strip_v2')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'w = ',num2str(P.w*1e9,'%.0f'),'nm, ',...
                'r = ',num2str(P.r*1e9,'%.0f'),'nm',...
                'hi = ',num2str(P.hi*1e9,'%.0f'),'nm, ',...
                'wi = ',num2str(P.wi*1e9,'%.0f'),'nm',...
                'ho = ',num2str(P.ho*1e9,'%.0f'),'nm, ',...
                'wo = ',num2str(P.wo*1e9,'%.0f'),'nm',...
                'r1 = ',num2str(P.r1*1e9,'%.0f'),'nm',...
                'r2 = ',num2str(P.r2*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'boomerang_lower')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'w = ',num2str(P.w*1e9,'%.0f'),'nm, ',...
                'r = ',num2str(P.r*1e9,'%.0f'),'nm',...
                'd = ',num2str(P.d*1e9,'%.0f'),'nm',...
                'h = ',num2str(P.h*1e9,'%.0f'),'nm',...
                'r1 = ',num2str(P.r1*1e9,'%.0f'),'nm',...
                'r2 = ',num2str(P.r2*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'snowflake')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'w = ',num2str(P.w*1e9,'%.0f'),'nm, ',...
                'r = ',num2str(P.r*1e9,'%.0f'),'nm',...
                'r1 = ',num2str(P.r1*1e9,'%.0f'),'nm',...
                'r2 = ',num2str(P.r2*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'hole')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'r = ',num2str(P.r*1e9,'%.0f'),'nm, ',...
                'b = ',num2str(P.b*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'hole_strip')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'r = ',num2str(P.r*1e9,'%.0f'),'nm, ',...
                'b = ',num2str(P.b*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'rib')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                's_',num2str(P.s*1e9,'%.0f'),'nm',...
                'w_',num2str(P.w*1e9,'%.0f'),'nm_', ...
                't_',num2str(P.t*1e9,'%.0f'),'nm_', ...
                'th_',num2str(P.th*1e9,'%.0f'),'nm_', ...
                'd_',num2str(P.d*180/pi,'%.0f'),'deg']}; 
        end
        title(bandtitle);
        box on
        hold off
        
        % save band diagram as .png and .fig
        pathFig = [P.datLoc,fBase,'_fullBands'];
        saveas(gcf,[pathFig,'.png']);
        saveas(gcf,[pathFig,'.fig']);
    else 
        figure; hold on
        maxFreqs = [0 0 0 0];

        p1 = plot(OpticalBand.k_norm,OpticalBand.F*1e-12,'ko','linewidth',2,'DisplayName','sym','MarkerSize',5);
        
        % plot the light line 
        hold on;
        lightx = linspace(0,1,100);
        lighty1 = lightx*(3e8)/(P.a*(1e12))/2;
        light1 = plot(OpticalBand.kx_norm,lightline*1e-12,'b-','linewidth',1);
        
        % plot optical bandgaps
        for k = 1:length(OpticalBand.gapSize)
            bgp = patch([0 1 1 0],(1e-12)*(OpticalBand.midGap(k) + 0.5*[OpticalBand.gapSize(k) ...
                OpticalBand.gapSize(k) -OpticalBand.gapSize(k) -OpticalBand.gapSize(k)]),180/255*[1 1 1],'EdgeColor','none');
            alpha(bgp,0.5);
        end
        
        % plot symmetric midgap frequencies
        for k = 1:length(OpticalBand.midGap)
            midfreqs = OpticalBand.midGap(k)*ones(length(OpticalBand.k_norm),1);
            plot(OpticalBand.k_norm,midfreqs*1e-12,'.--r','linewidth',0.5);
        end
      
        xlabel('k','FontSize',12);
        ylabel('Frequency (THz)','FontSize',12);
        amax = max([OpticalBand.F(:)])*1e-12;
        axis([0 1 0 amax]);
        %         axis tight
        set(gca,'XTick',[0; 1]);
        %         set(gca,'XTickLabel',{'G','C'},'fontname','symbol','fontsize',16)
        set(gca,'XTickLabel',{'\Gamma','X','M','\Gamma'},'fontsize',12)
        
        if strcmp(P.celltype,'2D_ribs')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'w = ',num2str(P.w*1e9,'%.0f'),'nm',...
                'hi = ',num2str(P.hi*1e9,'%.0f'),'nm, ',...
                'wi = ',num2str(P.wi*1e9,'%.0f'),'nm',...
                'ho = ',num2str(P.ho*1e9,'%.0f'),'nm, ',...
                'wo = ',num2str(P.wo*1e9,'%.0f'),'nm',...
                'ai = ',num2str(P.ai*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'cross')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'hc = ',num2str(P.hc*1e9,'%.0f'),'nm, ',...
                'wc = ',num2str(P.wc*1e9,'%.0f'),'nm',...
                'r1 = ',num2str(P.r1*1e9,'%.0f'),'nm',...
                'r2 = ',num2str(P.r2*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'boomerang_strip_v2')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'w = ',num2str(P.w*1e9,'%.0f'),'nm, ',...
                'r = ',num2str(P.r*1e9,'%.0f'),'nm',...
                'hi = ',num2str(P.hi*1e9,'%.0f'),'nm, ',...
                'wi = ',num2str(P.wi*1e9,'%.0f'),'nm',...
                'ho = ',num2str(P.ho*1e9,'%.0f'),'nm, ',...
                'wo = ',num2str(P.wo*1e9,'%.0f'),'nm',...
                'r1 = ',num2str(P.r1*1e9,'%.0f'),'nm',...
                'r2 = ',num2str(P.r2*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'snowflake')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'w = ',num2str(P.w*1e9,'%.0f'),'nm, ',...
                'r = ',num2str(P.r*1e9,'%.0f'),'nm',...
                'r1 = ',num2str(P.r1*1e9,'%.0f'),'nm',...
                'r2 = ',num2str(P.r2*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'boomerang_lower')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'w = ',num2str(P.w*1e9,'%.0f'),'nm, ',...
                'r = ',num2str(P.r*1e9,'%.0f'),'nm',...
                'd = ',num2str(P.d*1e9,'%.0f'),'nm',...
                'h = ',num2str(P.h*1e9,'%.0f'),'nm',...
                'r1 = ',num2str(P.r1*1e9,'%.0f'),'nm',...
                'r2 = ',num2str(P.r2*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'hole')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'hx = ',num2str(P.hx*1e9,'%.0f'),'nm, ',...
                'hy = ',num2str(P.hy*1e9,'%.0f'),'nm, ',...
                'th = ',num2str(P.th*1e9,'%.0f'),'nm, ',...
                'beamWidth = ',num2str(P.beam_width*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'hole_strip')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'r = ',num2str(P.r*1e9,'%.0f'),'nm, ',...
                'b = ',num2str(P.b*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'hole_strip_wvg')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'r = ',num2str(P.r*1e9,'%.0f'),'nm, ',...
                'b = ',num2str(P.b*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'Snowflake_strip_2d')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                'b = ',num2str(P.b*1e9,'%.0f'),'nm, ',...
                'bbase = ',num2str(P.b_base*1e9,'%.0f'),'nm, ',...
                'w = ',num2str(P.w*1e9,'%.0f'),'nm, ',...
                'r = ',num2str(P.r*1e9,'%.0f'),'nm',...
                'r1 = ',num2str(P.r1*1e9,'%.0f'),'nm',...
                'r2 = ',num2str(P.r2*1e9,'%.0f'),'nm',...
                'th = ',num2str(P.th*1e9,'%.0f'),'nm']};
        elseif strcmp(P.celltype,'rib')
            bandtitle = {['a = ',num2str(P.a*1e9,'%.0f'),'nm, ',...
                's_',num2str(P.s*1e9,'%.0f'),'nm',...
                'w_',num2str(P.w*1e9,'%.0f'),'nm_', ...
                't_',num2str(P.t*1e9,'%.0f'),'nm_', ...
                'th_',num2str(P.th*1e9,'%.0f'),'nm_', ...
                'd_',num2str(P.d*180/pi,'%.0f'),'deg']}; 
        else 
            bandtitle = 'blank title';
        end
        title(bandtitle);
        box on
        hold off
        
        % save band diagram as .png and .fig
        pathFig = [P.datLoc,fBase,'_fullBands'];
        saveas(gcf,[pathFig,'.png']);
        saveas(gcf,[pathFig,'.fig']);
end
end
    tEnd = toc(tStart);
    disp(['Simulation time = ',num2str(tEnd/60,'%.2f'),'mins'])
else
    disp('Data folder exists in working directory')
    ds.OpticalBand = [];
 
end